/**:
  ros__parameters:
    x_axis: 4
    y_axis: 3
    z_axis: 1
    yaw_axis: 0
    arm_button: 7
    disarm_button: 0
    takeoff_button: 6
    land_button: 0
    x_vel_max: 0.5
    y_vel_max: 0.5
    z_vel_max: 0.5
    yaw_vel_max: 0.1
